# -*- coding: utf-8 -*-
"""chatbotTA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZoVToRIvjUf2APy8toLmZ4mZ-2rwLUu0
"""

import pandas as pd
import nltk
import numpy as np
import string
import warnings
import requests
import pickle
import random

nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('omw-1.4')

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

"""TRAIN DATA"""

data = [["Hi",0],["Halo",0],["Hey",0],["Hai",0],["Hola",0],["Alo",0],["H4i",0],["H4lo",0],["H4l0",0],["Assalamualaikum",0],["Shalom",0],["Ola",0],["Nihao",0],["Bonjour",0],
        ["Apa sajakah obat untuk Covid-19?",1],["Apa obat untuk Covid?",1],["Obat Covid?",1],["Apa obat Covid?",1],["4p4 ob4t untuk mengatasi Covid?",1],["4pa 0bat untuk Corona?",1],["Ap4 s4j4 obat untuk C0vid?",1],["Ap s4ja obat untuk C0v1d?",1],["0b4t untuk C0v1d?",1],["0b4t utk C0v1d?",1],
        ["Apa itu Favipiravir?",2],["Favipiravir adalah?",2],["Favipiravir merupakan?",2],["Favipiravir itu apa?",2],["Apa yang dimaksud F4v1p1r4v1r?",2],["4p4 1tu F4vipiravir?",2],["4pa 1tu F4v1piravir?",2],["4p 1t F4vip1ravir?",2],["4p4 1tu F4vipir4vir?",2],
        ["Apa itu Molnupiravir?",3],["Molnupiravir adalah?",3],["Molnupiravir merupakan ?",3],["Molnupiravir itu apa ?",3],["M0lnupir4v1r adalah?",3],["M0lnup1r4v1r 4d4l4h?",3],["M0lnupiravir m3rup4k4n?",3],["4p 1t Molnup1ravir?",3],["4pa 1tu Molnup1r4vir?",3],["M0lnupirav1r 4dal4h?",3],["M0lnupir4vir 4dalah?",3],
        ["Apa itu Paxlovid?",4],["Paxlovid adalah?",4],["Paxlovid merupakan?",4],["Paxlovid itu apa?",4],["Apa yang dimaksud P4xl0v1d?",4],["P4xlovid adalah?",4],["P4xlovid 4d4l4h?",4],["Paxlovid m3rup4k4n?",4],["Paxlovid 1tu 4p4?",4],
        ["Bagaimana cara kerja Favipiravir?",5],["Cara kerja Favipiravir adalah?",5],["Gimana cara kerja Favipiravir?",5],["Cara kerja F4v1p1r4v1r adalah?",5],["F4vipiravir bekerja?",5],["F4v1piravir b3kerja b4g41m4n4?",5],["F4v1p1ravir bek3rja dengan cara?",5],["F4v1p1r4vir b3k3rj4 gimana?",5],["F4v1p1r4v1r bek3rj4?",5],["Cara krj F4v1p1r4v1r adlh?",5],["Cr kerja F4v1p1r4v1r adlh?",5],
        ["Bagaimana cara kerja Molnupiravir?",6],["Cara kerja Molnupiravir adalah?",6],["Gimana cara kerja Molnupiravir?",6],["Cara kerja M0lnup1r4v1r adalah?",6],["M0lnupir4v1r bekerja?",6],["M0lnupirav1r b3k3rj4 bagaimana?",6],["M0lnupiravir b3kerj4 dengan cara?",6],["M0lnup1ravir b3kerja gimana?",6],["M0lnup1rav1r bekerja bagiamana?",6],["Cara krj M0lnup1r4v1r adlh?",6],["Cr kerja M0lnup1r4v1r adlh?",6],
        ["Bagaimana cara kerja Paxlovid?",7],["Cara kerja Paxlovid adalah?",7],["Gimana cara kerja Paxlovid?",7],["Cara kerja P4xl0v1d adalah?",7],["Cara kerja P4xl0v1d adalah?",7],["P4xlov1d bek3rj4?",7],["P4xlovid b3k3rj4 bagaimana?",7],["P4xl0vid bekerja dengan cara?",7],["Paxl0v1d bekerja gimana?",7],["Paxlov1d bekerja bagaimana?",7],["Cara krj Paxlov1d adlh?",7],["Cr kerja Paxlov1d adlh?",7],
        ["Apa efek samping dari penggunaan Favipiravir?",8],["Efek samping dari penggunaan Favipiravir adalah?",8],["Efek samping dari penggunaan F4v1p1r4v1r adalah?",8],["Efek samping Favipiravir?",8],["3f3k s4mp1ng F4vipiravir apa?",8],["Efek samp1ng F4v1piravir itu apa?",8],["Efek samping F4v1p1ravir itu gimana?",8],["Efek samping F4v1p1r4vir?",8],["Efek samping F4v1p1r4v1r apa?",8],["Efk smpg F4v1p1r4v1r ap?",8],
        ["Apa efek samping dari penggunaan Molnupiravir?",9],["Efek samping dari penggunaan Molnupiravir adalah?",9],["3f3k s4mp1ng d4r1 p3nggun44n M0lnup1r4v1r adalah?",9],["Efek samping M0lnup1r4v1r?",9],["3f3k s4mp1ng M0lnupir4v1r apa?",9],["Ef3k samp1ng M0lnupirav1r itu apa?",9],["Efek s4mp1ng M0lnupir4v1r itu gimana?",9],["Efek s4mping M0lnupir4vir?",9],["Efek samping M0lnup1r4vir?",9],["Efk smpg M0lnup1r4vir ap?",9],
        ["Apa efek samping dari penggunaan Paxlovid?",10],["Efek samping dari penggunaan Paxlovid adalah?",10],["Efek samping dari penggunaan P4xl0v1d adalah?",10],["Efek samping P4xl0v1d?",10],["3fek s4mp1ng Paxl0v1d apa?",10],["Ef3k samp1ng Paxlov1d itu apa?",10],["3fek s4mping P4xlov1d itu gimana?",10],["Efek samping P4xlov1d?",10],["Efk smpg P4xlov1d ap?",10],
        ["Bagaimana cara penggunaan Favipiravir?",11],["Cara penggunaan Favipiravir adalah?",11],["Cara penggunaan F4v1p1r4v1r adalah?",11],["Cara pakai F4v1p1r4v1r?",11],["C4ra p4kai F4v1p1r4v1r?",11],["Cara pakai F4vipir4v1r gimana?",11],["Cara pakai F4v1piravir gimana?",11],["Cara pakai Fav1p1r4v1r itu bagaimana?",11],["Cara pakai Favipirav1r itu gimana?",11],["Cr pk Favipirav1r itu gmn?",11],
        ["Bagaimana cara penggunaan Molnupiravir?",12],["Cara penggunaan Molnupiravir adalah?",12],["Cara penggunaan M0lnup1r4v1r adalah?",12],["Cara pakai M0lnup1r4v1r?",12],["C4ra p4k4i M0lnupir4v1r?",12],["Cara pakai M0lnupirav1r gimana?",12],["Cara pakai M0lnupiravir itu gimana?",12],["Cara pakai M0lnupirav1r itu bagaimana?",12],["Cr pk M0lnupirav1r itu gmn?",12],
        ["Bagaimana cara penggunaan Paxlovid?",13],["C4r4 p3nggun44n Paxlovid adalah?",13],["C4ra penggunaan P4xl0v1d adalah?",13],["Car4 pakai P4xl0v1d?",13],["Car4 pakai P4xl0v1d?",13],["Car4 p4k41 P4xlov1d?",13],["Cr pk P4xl0v1d?",13],["Car4 pakai P4xl0v1d?",13],["Car4 pakai P4xl0v1d?",13],["Cr pkP4xl0v1d itu gmn?",13],
        ["Bagaimana cara membeli Favipiravir?",14],["C4r4 membeli Favipiravir adalah?",14],["C4ra m3mb3l1 F4v1p1r4v1r adalah?",14],["Car4 b3l1 F4v1p1r4v1r?",14],["Beli F4vipiravir dimana?",14],["Beli Favip1r4v1r dimana?",14],["Beli Fav1p1r4v1r ada dimana?",14],["Beli Fav1p1rav1r itu dimana?",14],["Beli Fav1p1ravir mana?",14],["Bl Fav1p1ravir dmn?",14],
        ["Bagaimana cara membeli Molnupiravir?",15],["Cara membeli Molnupiravir adalah?",15],["Cara membeli Molnup1r4v1r adalah?",15],["Cara beli M0lnupirav1r adalah?",15],["Beli M0lnup1rav1r dimana?",15],["Beli M0lnup1r4vir ada dimana?",15],["Beli M0lnup1ravir itu dimana?",15],["Beli Molnup1r4vir mana?",15],["Bl Molnup1r4vir dmn?",15],
        ["Bagaimana cara membeli Paxlovid?",16],["Cara membeli Paxlovid adalah?",16],["Cara membeli P4xl0vid adalah?",16],["Cara beli P4xlov1d adalah?",16],["Beli P4xl0v1d dimana?",16],["Beli Paxl0v1d itu dimana?",16],["Beli P4xl0v1d ada dimana?",16],["Beli P4xl0vid mana?",16],["Beli Paxl0vid mana?",16],["Bl Paxl0vid dmn?",16],
        ["Berapa komposisi Favipiravir?",17],["Komposisi Favipiravir adalah?",17],["Komposisi Fav1p1r4v1r adalah?",17],["Komposisi Favip1r4v1r?",17],["Apa komposisi F4v1p1r4v1r?",17],["Berapa komposisi F4vip1r4vir?",17],["Apa kandungan F4vipirav1r?",17],["Kandungan Favipirav1r?",17],["Brp komposisi F4vip1r4vir?",17],
        ["Berapa komposisi Molnupiravir?",18],["Komposisi Molnupiravir adalah?",18],["Komposisi Molnupirav1r 4d4l4h?",18],["Komposisi Molnup1r4v1r?",18],["Apa komposisi M0lnup1r4v1r?",18],["Berapa komposisi Molnup1r4vir?",18],["Apa kandungan Molnupir4v1r?",18],["Kandungan Molnup1rav1r?",18],["Brp komposisi Molnup1r4vir?",18],
        ["Berapa komposisi Paxlovid?",19],["Komposisi Paxlovid adalah?",19],["Komposisi P4xl0vid adalah?",19],["Komposisi P4xlovid?",19],["Apa komposisi Paxl0vid?",19],["Komposisi Paxl0v1d?",19],["Berapa komposisi Paxl0v1d?",19],["Apa kandungan Paxlov1d?",19],["Kandungan P4xl0vid?",19],["Brp komposisi Paxl0v1d?",19],
        ["Berapa harga Favipiravir?",20],["Harga Favipiravir adalah?",20],["Harga Fav1p1r4v1r?",20],["Harga Favip1r4v1r berapa?",20],["Harga F4v1p1r4vir itu berapa?",20],["Harga F4v1p1ravir berapa?",20],["Harga F4v1piravir?",20],["Hrg F4v1p1ravir brp?",20],
        ["Berapa harga Molnupiravir?",21],["Harga Molnupiravir adalah?",21],["Harga Molnup1rav1r?",21],["Harga Molnup1r4v1r berapa?",21],["Harga Molnupirav1r berapa?",21],["Harga M0lnup1rav1r itu berapa?",21],["Harga M0lnup1ravir?",21],["Hrg Molnupirav1r brp?",21],
        ["Berapa harga Paxlovid?",22],["Harga Paxlovid adalah?",22],["Harga P4xl0v1d?",22],["Harga Paxlov1d berapa?",22],["Harga Paxl0v1d berapa?",22],["Harga Paxl0vid itu berapa?",22],["Harga P4xl0vid?",22],["Hrg Paxl0vid itu brp?",22],
        ["Siapa yang boleh mengkonsumsi Favipiravir?",23],["Yang boleh mengkonsumsi Favipiravir adalah?",23],["Yang boleh mengkonsumsi Fav1p1r4v1r?",23],["Untuk siapa F4v1p1r4v1r?",23],["Siapa boleh konsumsi F4v1p1r4v1r?",23],["Untuk siapa Favipiravir?",23],["Utk sp Favipiravir?",23],
        ["Siapa yang boleh mengkonsumsi Molnupiravir?",24],["Yang boleh mengkonsumsi Molnupiravir adalah?",24],["Yang boleh mengkonsumsi Molnup1r4v1r?",24],["Untuk siapa M0lnup1r4v1r?",24],["Siapa boleh konsumsi Molnup1ravir?",24],["Untuk siapa Molnupiravir?",24],["Utk sp Molnupiravir?",24],
        ["Siapa yang boleh mengkonsumsi Paxlovid?",25],["Yang boleh mengkonsumsi Paxlovid adalah?",25],["Yang boleh mengkonsumsi Paxl0v1d?",25],["Untuk siapa P4xl0vid?",25],["Siapa boleh konsumsi Paxl0v1d?",25],["Untuk siapa Paxlovid?",25],["Utk sp Paxlovid?",25],
        ["Goodbye",26],["Byebye",26],["Bye",26],["Bye",26],["Sampai jumpa",26],["Selamat tinggal",26],
        ["Thanku",27],["Thank You",27],["Thanks",27],["Terima Kasih",27],["Trims",27],["Thank you so much",27],["Arigato",27],["Merci",27],["Gracias",27],["Danke",27],["Xie-xie",27]]

df = pd.DataFrame(data, columns = ["Text","Intent"])
df

"""TEXT PROCESSING

"""

lemmer = nltk.stem.WordNetLemmatizer()

def LemTokens(tokens):
    return [lemmer.lemmatize(token) for token in tokens]

remove_punct_dict = dict((ord(punct), None) for punct in string.punctuation)

def Normalize(text):
    return LemTokens(nltk.word_tokenize(text.lower().translate(remove_punct_dict)))

"""TRAINING MODEL"""

x = df['Text']
y = df['Intent']

vectorizer = TfidfVectorizer()

X = vectorizer.fit_transform(x)

# fit model Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split 
lr = LogisticRegression()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
print(X_test)

a = lr.predict_proba(X_test)
print(a)

"""MEMBUAT RESPON UNTUK SETIAP INTENT"""

responses = {0 : {"intent":"greetings","response":['Selamat Datang di Layanan Informasi Covid',]}, 
      1 : {"intent":"obat","response":['Favipiravir, molnupiravir, dan paxlovid merupakan 3 jenis obat antivirus yang diberikan kepada pasien COVID-19 di Indonesia. 3 jenis obat antivirus tersebut adalah obat yang boleh diresepkan.']},
      2 : {"intent":"obat","response":['Favipiravir atau t705 atau 6-fluoro-3-hydroxy-2-pyrazinecarboxamide merupakan obat turunan dari pyrazinecarboxamide.']},
      3 : {"intent":"obat","response":['Molnupiravir adalah obat antivirus baru yang sedang diteliti potensinya untuk mengobati COVID-19. Pengobatan COVID-19 dengan molnupiravir telah mendapatkan izin pemakaian darurat, baik dari FDA maupun BPOM.']},
      4 : {"intent":"obat","response":['Paxlovid adalah merek dagang dari kombinasi antivirus PF-07321332 dan ritonavir yang dikembangkan oleh Pfizer sebagai obat penyakit COVID-19.']},
      5 : {"intent":"obat","response":['Favipiravir bekerja melawan virus RNA dengan menghambat enzim polimerasi, sehingga virus tidak dapat berkembang biak.']},
      6 : {"intent":"obat","response":['Molnuporavir bekerja dengan cara mengganggu aktivitas enzim RNA virus Corona sehingga dapat menghambat perkembangbiakan virus tersebut. Setelah itu, virus Corona akan dibasmi oleh sistem kekebalan tubuh penderita hingga akhirnya musnah sepenuhnya.']},
      7 : {"intent":"obat","response":['Paxlovid mengandung antivirus baru, yaitu PF-07321332, yang bekerja dengan cara memblokir aktivitas protease SARS-CoV-2-3CL atau enzim yang menyebabkan virus Corona bereplikasi. Antivirus baru ini akan menghambat replikasi virus pada tahap proteolisis yang terjadi sebelum replikasi RNA virus.']},
      8 : {"intent":"obat","response":['Favipiravir dapat menyebabkan penurunan kualitas sperma dan kecacatan pada janin. Oleh karena itu, konsultasikan dengan dokter bila Anda sedang hamil atau merencanakan kehamilan.']},
      9 : {"intent":"obat","response":['Diare, mual, dan pusing setelah dikonsumsi. Selain itu, molnupiravir juga tidak direkomendasikan untuk digunakan selama kehamilan. Sebab, studi yang dilakukan terhadap hewan menunjukkan bahwa molnupiravir dapat menyebabkan kerusakan janin bila diberikan pada individu hamil.']},
      10 : {"intent":"obat","response":['Paxlovid dapat menyebabkan gangguan indra perasa, diare, tekanan darah tinggi, dan nyeri otot.']},
      11 : {"intent":"obat","response":['Menurut penelitian yang sedang dilakukan, favipiravir diberikan dalam dosis 1.600 mg sebanyak 2 kali sehari pada hari pertama, dilanjutkan dengan 600 mg sebanyak 2 kali sehari pada hari ke-2 hingga hari ke-5.']},
      12 : {"intent":"obat","response":['Obat Molnupiravir memiliki dosis 2x800 mg berjumlah 40 tablet untuk diminum pasien dengan dosis 2x4 tablet per hari.']},
      13 : {"intent":"obat","response":['Selama uji klinis, Paxlovid diberikan secara oral setiap 12 jam sekali selama 5 hari kepada penderita COVID-19 dengan gejala ringan hingga sedang dan memiliki setidaknya satu kondisi medis yang bisa memperparah penyakit. Pemberian obat antivirus Paxlovid ini dilakukan sejak timbulnya gejala.']},
      14 : {"intent":"obat","response":['Favipiravir hanya tersedia dengan resep dokter.']},
      15 : {"intent":"obat","response":['Molnupiravir hanya tersedia dengan resep dokter.']},
      16 : {"intent":"obat","response":['Paxlovid hanya tersedia dengan resep dokter.']},
      17 : {"intent":"obat","response":['Setiap tablet Favipiravir mengandung 200mg.']},
      18 : {"intent":"obat","response":['Setiap tablet Molnupiravir mengandung 200mg.']},
      19 : {"intent":"obat","response":['Paxlovid akan tersedia dalam bentuk blister berisi dua tablet Nirmatrelvir 150 mg, dan satu tablet Ritonavir 100 mg. Ritonavir merupakan obat untuk HIV, tetapi di sini digunakan untuk memperlambat metabolisme nirmatrelvir.']},
      20 : {"intent":"obat","response":['Harga Obat Favipiravir Rp215.800 - Rp225.100 Per Strip']},
      21 : {"intent":"obat","response":['Harga Obat Molnupiravir Rp175.000 - Rp236.600 Per Strip']},
      22 : {"intent":"obat","response":['Harga dari obat Paxlovid belum diumukan.']},
      23 : {"intent":"obat","response":['Favipiravir dapat diberikan kepada pasien dewasa COVID-19 dengan gejala ringan, sedang, dan parah. . Obat ini tidak boleh diberikan kepada ibu hamil atau wanita yang sedang merencanakan kehamilan karena dapat menyebabkan cacat bawaan pada bayi.']},
      24 : {"intent":"obat","response":['Molnupiravir dapat diberikan pada pasien COVID-19 berusia 18 tahun ke atas atau termasuk dalam kelompok berisiko tinggi, seperti penderita kanker, AIDS, penyakit liver, atau penyakit autoimun, menjalani kemoterapi dalam 12 bulan terakhir, atau pernah menjalani tranplantasi organ.']},
      25 : {"intent":"obat","response":['Paxlovid bisa diberikan pada pasien COVID-19 dengan gejala ringan hingga sedang. Obat antivirus ini juga boleh diberikan pada anak usia 12 tahun ke atas dengan berat badan setidaknya 40 kg.']},
      26 : {"intent":"goodbye","response":['Goodbye','Byebye','Bye','Have a good day, Sampai jumpa']},
      27 : {"intent":"thankyou","response":['Sama - sama']}}

"""MENGAKTIFKAN TELEGRAM BOT"""

import json
token = "5494138287:AAGoee47l6wNuI4naRUwIMkgA4LZtgyjnBA"

class telegram_bot():
    def __init__(self):
        self.token=token 
        self.url = f"https://api.telegram.org/bot{self.token}"

    def get_updates(self,offset=None):
        url = self.url+"/getUpdates?timeout=100"
        if offset:
            url = url+f"&offset={offset+1}"
        url_info = requests.get(url)
        return json.loads(url_info.content)
    def send_message(self,msg,chat_id):
        url = self.url + f"/sendMessage?chat_id={chat_id}&text={msg}"
        if msg is not None:
            requests.get(url)

    def grab_token(self):
        return tokens

"""DEPLOY BOT DAN MELAKUKAN REPLY"""

# Untuk dapat response

def response(user_response):
    text_test = [user_response]
    X_test = vectorizer.transform(text_test)
    prediction = lr.predict(X_test)
    reply = random.choice(responses[prediction[0]]['response'])
    return reply

# Untuk dapat intent
def intent(user_response):
    text_intent = [user_response]
    X_test_intent = vectorizer.transform(text_intent)
    predicted_intent = lr.predict(X_test_intent)
    intent_predicted = responses[predicted_intent[0]]['intent']
    return intent_predicted

import random

def bot_initialize(user_msg):
    flag=True
    while(flag==True):
        user_response = user_msg
        
        user_intent = intent(user_response)
        
        if(user_intent != 'goodbye'):
            if(user_response == '/start'):
                resp = """Selamat datang di Layanan Informasi Covid"""
                return resp
            
            elif (user_intent == 'greetings'):
                resp = str(random.choice(responses[0]['response']))
                return resp
        
            elif(user_intent == 'thankyou'):
                resp = random.choice(responses[27]['response'])
                return resp
            
            elif(user_intent == 'goodbye'):
                resp = random.choice(responses[26]['response'])
                return resp
            
            elif(user_intent == "obat"):
                user_response=user_response.lower()
                resp = response(user_response)
                return resp
            
            else:
                resp = "Saya tidak mengerti yang anda maksud. Coba tanyakan hal lain"
                return resp
            
        else:
            flag = False
            resp = "Saya tidak mengerti yang anda maksud. Coba tanyakan hal lain"
            return resp

tbot = telegram_bot()

update_id = None

def make_reply(msg):
    if msg is not None:
        reply = bot_initialize(msg)
    return reply


while True:
    print("...")
    updates = tbot.get_updates(offset=update_id)
    updates = updates['result']
    print(updates)
    if updates:
        for item in updates:
            update_id = item["update_id"]
            print(update_id)
            try:
                message = item["message"]["text"]
                print(message)
            except:
                message = None
            from_ = item["message"]["from"]["id"]
            print(from_)

            reply = make_reply(message)
            tbot.send_message(reply,from_)